### PR TITLE
Fix for Scrolling Upward

### PR DESCRIPTION
**Pull request by johnlk**
The scrollTop function is doing something super goofy and you might change my code later, but it works for now. Scrolling up is always off proportionate to the screen size, and this is how I solved it.

### CODE REVIEW

**Comment by aviaryan** [comment]
@johnlk Is it related to #1 ?

**Comment by johnlk** [comment]
@aviaryan Yes, my fix is for #1

**Comment by ansarimofid** [comment]
@johnlk Thanks for your contribution. The scrollTop is working fine if **sidebar link** is used to navigate. But if doesn't work as expected when **footer link** is clicked. Can you look into this issue. It would be great help if you can solve this.

**Comment by johnlk** [comment]
Oh shoot, I didn't even see the footer. Sure thing. I can look at it tomorrow morning.

**Pull request merged**
